import { NextResponse } from 'next/server';
import { createClient } from 'redis';
import { randomInt, createHash } from 'crypto';

const allowedEmails = new Set([
'adamjones123@hotmail.co.uk','ashutosh.saxena23@gmail.com','faizamuskan.fm@gmail.com','gupta.sweta2403@gmail.com','kanishkakul0106@gmail.com','likhithagompa@gmail.com','namratagupta188@gmail.com','naveenmeher07@gmail.com','nikhiljain2112@gmail.com','nvbadrinarayanan@gmail.com','rahulaneja687@gmail.com','rohit3864@gmail.com','sayan.chanda.2020@gmail.com','shafeeq.rahman01@gmail.com','shivisaggi@gmail.com','vrindagrover10@gmail.com','shanky442@gmail.com','pragyarch@gmail.com','suvarnamondal27@gmail.com'
]);
let clientPromise;
async function redis(){if(!clientPromise){const client=createClient({url:process.env.REDIS_URL});client.on('error',console.error);clientPromise=client.connect().then(()=>client).catch(e=>{clientPromise=undefined;throw e;});}return clientPromise;}
const hash=(email,code)=>createHash('sha256').update(`${email}:${code}`).digest('hex');
export async function POST(request){try{const {email}=await request.json();const id=String(email||'').trim().toLowerCase();if(!allowedEmails.has(id))return NextResponse.json({error:'Guest not found.'},{status:404});if(!process.env.BREVO_API_KEY)return NextResponse.json({error:'Email service is not configured.'},{status:500});const r=await redis();const cooldown=`babyq:otp:cooldown:${id}`;if(await r.get(cooldown))return NextResponse.json({error:'Please wait a minute before requesting another code.'},{status:429});const code=String(randomInt(100000,1000000));await Promise.all([r.set(`babyq:otp:${id}`,hash(id,code),{EX:600}),r.set(cooldown,'1',{EX:60})]);const response=await fetch('https://api.brevo.com/v3/smtp/email',{method:'POST',headers:{'accept':'application/json','api-key':process.env.BREVO_API_KEY,'content-type':'application/json'},body:JSON.stringify({sender:{name:'BabyQ 🤫',email:'suvarnamondal27@gmail.com'},to:[{email:id}],subject:'Your BabyQ secret code 🤫',htmlContent:`<div style="font-family:Arial,sans-serif;max-width:520px;margin:auto;padding:28px;color:#34271f"><p style="font-size:12px;font-weight:bold;letter-spacing:2px;color:#8a6334">BABYQ • TOP SECRET</p><h1 style="font-family:Georgia,serif;color:#704323">Your secret code</h1><p>Use this code to continue your BabyQ mission:</p><div style="font-size:36px;font-weight:800;letter-spacing:8px;margin:28px 0;color:#7c4b2a">${code}</div><p>This code expires in <strong>10 minutes</strong>.</p><p style="color:#8c7d70">If you didn’t request this, you can safely ignore this email. And no peeking at anyone else’s secret. 👀</p></div>`})});if(!response.ok){console.error('Brevo send failed',response.status,await response.text());await r.del(`babyq:otp:${id}`);return NextResponse.json({error:'Could not send the code. Please try again.'},{status:502});}return NextResponse.json({sent:true});}catch(error){console.error('OTP send error',error);return NextResponse.json({error:'Could not send the code. Please try again.'},{status:500});}}
